"""Process-wide settings — module-level constants.

Per-user settings (provider, api_key, model) live at
``~/.config/voitta-compute/settings.json`` and are read at
chat-start by ``app.settings``.

The base system prompt is no longer a constant here — it lives in
``plugins/default/system.md`` and is contributed via the plugin loader
(default plugin matches ``host_patterns: ["*"]`` so it always applies).
"""

from __future__ import annotations

import os
from pathlib import Path

HOST = "127.0.0.1"
PORT = 12358

# When running as a packaged .app the launcher sets VOITTA_PROJECT_ROOT to
# ~/Library/Application Support/Voitta Compute/backend so all derived paths
# (certs, rag, plugins, docs) resolve into the writable user data dir rather
# than the read-only bundle.
_env_root = os.environ.get("VOITTA_PROJECT_ROOT")
PROJECT_ROOT = Path(_env_root) if _env_root else Path(__file__).resolve().parents[1]

# Mutable user data (scripts, python_storage) always lives in Application
# Support — never inside the source tree or the read-only .app bundle.
USER_DATA_ROOT = Path.home() / "Library" / "Application Support" / "Voitta Compute" / "backend"
TLS_CERT_PATH = PROJECT_ROOT / "certs" / "127.0.0.1+1.pem"
TLS_KEY_PATH = PROJECT_ROOT / "certs" / "127.0.0.1+1-key.pem"

USER_CONFIG_DIR = Path.home() / ".config" / "voitta-compute"
USER_SETTINGS_PATH = USER_CONFIG_DIR / "settings.json"

# Plugins live at the REPO root (sibling of backend/ and frontend/), not
# inside backend/. Both the BE loader (here) and the FE Vite glob read
# from the same tree so plugin authors have a single source of truth.
PLUGINS_DIR = PROJECT_ROOT.parent / "plugins"

# Frontend dist — the compiled React bundle served at /.
# desktop.py sets VOITTA_FRONTEND_DIST to the bundle-internal path before
# uvicorn starts; in dev it falls back to frontend/dist next to backend/.
_env_fe = os.environ.get("VOITTA_FRONTEND_DIST")
FRONTEND_DIST = Path(_env_fe) if _env_fe else PROJECT_ROOT.parent / "frontend" / "dist"

# Project-wide prose docs (indexed by the RAG builder alongside every
# plugin's docs/ tree).
DOCS_DIR = PROJECT_ROOT.parent / "docs"

# Built RAG indexes — Chroma persistent store + BM25 + manifest.json.
# Generated by ``scripts/build_rag.py``; gitignored.
RAG_DIR = PROJECT_ROOT.parent / "rag"

# Agent-loop knobs.
# Default cap on assistant tokens per LLM call. User-overridable via
# the Global settings tab (``max_tokens``); the agent loop reads the
# effective value from ``app.settings.load()`` at the start of each turn.
DEFAULT_MAX_TOKENS = 24576
# Default cap on tool-use iterations per user turn. User-overridable
# via the Global settings tab (``max_tool_iterations``); the agent
# loop reads the effective value from ``app.settings.load()``.
DEFAULT_MAX_TOOL_ITERATIONS = 25
